# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e228a1ead2e443acf04087dadec0c036ce19dd22c48c07cee68c16f3a671ad69dac7eff2c289435eb82b02982338695b352e73f8bae9ebce552b18fb92dae6db

test:
  secret_key_base: 734c770c86e7554969ae80f19de8c67ae8bfb2735e4fc460a3d9e396cff80ced6d69ae128c6e6871bc8793699db208643cfd8ee72a0b715a848452817cf75765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
